Repository Proxima-Project/Proxi-BoS-Bay12, pull requests merged in 2022-10, with the labels that each got.

#83 New sprites
  baystation12.dme
  icons/bos/obj/armorshield.dmi
Labels: Sprites

#82 ГКК, Шеллы и пушки
  code/__defines/guns.dm
  code/controllers/communications.dm
  code/game/machinery/telecomms/presets.dm
  code/modules/boh/fabrication/weaponsfab.dm
  code/modules/mob/living/say.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/research/designs/designs_circuits.dm
  code/modules/species/shell/shell.dm
  maps/torch/infantry/firearms.dm
  maps/torch/infantry/hardsuit.dm
  maps/torch/infantry/outfits.dm
  maps/torch/items/encryption_keys.dm
  maps/torch/items/machinery.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/structures/closets/misc.dm
  maps/torch/torch6_bridge.dmm
  modular_mithra/code/modules/clothing/spacesuits/rig/suits/station.dm
  proxima/code/game/items/weapons/gun/energy/k342.dm
  proxima/code/game/items/weapons/projectile/infinity-ammuntion.dm
  proxima/code/game/items/weapons/projectile/infinity-guns.dm
  proxima/icons/obj/guns/guns.dmi
Labels: Map, Sprites

#76 Как я перестал бояться и полюбил лодаут
  baystation12.dme
  code/bos/modules/clothing/blazer.dm
  code/bos/modules/clothing/cyberpunk_overcoat.dm
  code/bos/modules/clothing/peacoat.dm
  code/bos/modules/clothing/sexysuits.dm
  code/datums/supplypacks/nonessent.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  icons/bos/mob/onmob/onmob_head.dmi
  icons/bos/mob/onmob/onmob_suit.dmi
  icons/bos/obj/clothing/obj_head.dmi
  icons/bos/obj/clothing/obj_suit.dmi
Labels: Sprites

#91 Вилка для БоСа
  .github/workflows/test.yml
  code/bos/game/objects/effects/razorweb.dm
  code/bos/modules/overmap/_defines.dm
  code/game/objects/items/devices/scanners/health.dm
  modular_mithra/code/modules/mob/inventory.dm
  modular_mithra/code/modules/virus2/admin.dm
  modular_mithra/code/modules/virus2/antibodies.dm
  modular_mithra/code/modules/virus2/disease2.dm
  modular_mithra/code/modules/virus2/isolator.dm
  test/check-paths.sh
  test/run-test.sh
Labels: Repo

#94 Coiscin second custom
  customs/code/coiscin.dm
  customs/icons/mob/custom_items_lhand.dmi
  customs/icons/mob/custom_items_mob.dmi
  customs/icons/mob/custom_items_rhand.dmi
  customs/icons/obj/custom_items_obj.dmi
Labels: Sprites

#85 акценты
  baystation12.dme
  code/modules/client/preference_setup/background/02_language.dm
  code/modules/client/preferences.dm
  code/modules/culture_descriptor/_culture.dm
  code/modules/culture_descriptor/culture/cultures_human.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/language/accent/_accent.dm
  code/modules/mob/language/accent/adherent.dm
  code/modules/mob/language/accent/diona.dm
  code/modules/mob/language/accent/gcc.dm
  code/modules/mob/language/accent/misc.dm
  code/modules/mob/language/accent/serpentid.dm
  code/modules/mob/language/accent/skrell.dm
  code/modules/mob/language/accent/sol.dm
  code/modules/mob/language/accent/sol_other.dm
  code/modules/mob/language/accent/unathi.dm
  code/modules/mob/language/accent/vox.dm
  code/modules/mob/language/alien/adherent.dm
  code/modules/mob/language/alien/diona.dm
  code/modules/mob/language/alien/monkey.dm
  code/modules/mob/language/alien/serpentid.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/synthetic.dm
  code/modules/mob/mob_defines.dm
  icons/accents.dmi
Labels: Sprites

#100 Исправление у труб в чекпоинте рядом мемориалом
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
Labels: Map

#107 Tweak: armor for fleet
  .vscode/settings.json
  maps/torch/bos/items/clothing/lordania-feet.dm
  maps/torch/loadout/_defines.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_accessories_boh.dm
  maps/torch/loadout/loadout_eyes.dm
  maps/torch/loadout/loadout_gloves.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_shoes.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/loadout/loadout_suit_boh.dm
  maps/torch/loadout/loadout_uniform.dm
  maps/torch/loadout/loadout_xeno.dm
  maps/torch/loadout/~defines.dm
  maps/torch/torch.dm
Labels: Repo

#108 Temporary comment 'check unit tests contains all maps'
  test/check-paths.sh
  test/run-test.sh
Labels: Repo

#109 Add ability to statues to store items
  maps/torch/bos/structures/statue.dm
  maps/torch/torch5_deck1.dmm
Labels: Map

#110 Add pilot's icon to sec huds
  maps/torch/icons/assignment_hud_boh.dmi
Labels: Sprites
